/**
 * The worked example on the landing page.
 *
 * A product page for this has to show a finished crawl, and the only honest way to do that is to
 * ship a real one. `fixtures/golden/demo-habitkit.json` is the recorded HabitKit crawl run through
 * the same registry the worker uses — regenerated by `npm run golden`, never hand-written. Rule #1
 * applies most strictly on the most visible surface the project has.
 *
 * It is a static import rather than a file read so the page prerenders: no database, no worker, no
 * filesystem at request time. The page is therefore always up, which the live crawl path is not.
 */

import raw from "../fixtures/golden/demo-habitkit.json" with { type: "json" };
import type { AppIdentity, Coverage, Event, Metric } from "./schema.ts";
import { computeInsights } from "./insights.ts";
import { buildBrief } from "./brief.ts";
import { attributionSummary, buildSteps } from "./impact.ts";

export interface DemoCrawl {
  /** The day the fixtures were recorded. Shown, so nothing implies the numbers are live. */
  recorded_at: string;
  app: AppIdentity;
  events: Event[];
  metrics: Metric[];
  coverage: Coverage[];
}

const crawl = raw as unknown as DemoCrawl;

const insights = computeInsights(crawl.events, crawl.metrics);
const steps = buildSteps(crawl.events, crawl.metrics);

export const DEMO = {
  ...crawl,
  insights,
  steps,
  brief: buildBrief(crawl.app.name, crawl.events, crawl.metrics, insights, steps),
  attribution: attributionSummary(steps),
  /** Sources that returned rows, over sources attempted. The honest denominator. */
  sources_ok: crawl.coverage.filter((c) => c.status === "ok" || c.status === "partial").length,
  span: {
    from: crawl.events[0]?.date.slice(0, 4) ?? "",
    to: crawl.events.at(-1)?.date.slice(0, 4) ?? "",
  },
};
